server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost/vendas?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: user
    password: user    
  flyway:
    locations: classpath:db/migration, classpath:db/data
    flyway:
      url: jdbc:mysql://${embedded.mysql.host}:${embedded.mysql.port}/vendas
      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
      user: user
      password: user     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          default_schema: vendas
 